mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('products.urls')),
                  path('logout/', views.LogoutView.as_view(next_page='/'), name='logout')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('Category/<slug:slug>/', views.show_category, name='category'),
    path('Category/<slug:slug>/', views.show_category, name='show_category'),
    path('Product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('faq/', views.faq, name='faq'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('about_us/', views.about_us, name='about_us'),
    path('services/', views.services, name='services'),
    path('search/', views.search, name='search'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('user/', views.user, name='user'),
    path('user/update_profile', views.update_profile, name='update_profile'),
    path('user/update_address', views.update_address, name='update_address'),
    path('user/update_profile_pic', views.update_profile_pic, name='update_profile_pic'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist_update/<int:product_id>', views.wishlist_update, name='wishlist_update'),
    path('cart/', views.cart, name='cart'),
    path('cart_update/<int:product_id>', views.cart_update, name='cart_update'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_history/', views.order_history, name='order_history'),
    path('order_history_update/', views.order_history_update, name='order_history_update'),
    path('track_order/<int:order_id>', views.track_order, name='track_order'),
    path('admin_page/', views.admin_page, name='admin_page'),
    path('admin_product_page/<int:order_id>', views.admin_product_page, name='admin_product_page'),
    path('admin_status_update/<int:order_id>/<str:status>', views.admin_status_update, name='admin_status_update'),
    path('user/notification', views.notification, name='notification'),
    path('user/notification_info/<int:notification_id>', views.notification_info, name='notification_info'),
    path('user/notification_close/<int:pk>', views.notification_close, name='notification_close'),
]

products/models.py
from django.db import models
from mptt.models import TreeForeignKey, MPTTModel
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class Product(models.Model):
    title = models.CharField(max_length=100)
    category = TreeForeignKey('Category', null=True, blank=True, on_delete=models.CASCADE)
    image_url_1 = models.ImageField(upload_to='product/img', null=True, blank=True)
    image_url_2 = models.ImageField(upload_to='product/img', null=True, blank=True)
    image_url_3 = models.ImageField(upload_to='product/img', null=True, blank=True)
    offer_price = models.FloatField(default=0)
    original_price = models.FloatField(default=0)
    description = models.TextField(null=True, blank=True)
    quantity_left = models.IntegerField(null=True, blank=True)
    return_days = models.IntegerField(null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)

    def get_product_id(self):
        return self.id

    def __str__(self):
        return self.title


class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True,
                            on_delete=models.CASCADE)
    image_url = models.ImageField(upload_to='category/img', null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        unique_together = ('parent', 'slug')
        verbose_name_plural = 'categories'

    def get_slug_list(self):
        try:
            ancestors = self.get_ancestors(include_self=True)
        except:
            ancestors = []
        else:
            ancestors = [i.slug for i in ancestors]
        slugs = []
        for i in range(len(ancestors)):
            slugs.append('/'.join(ancestors[:i + 1]))
        return slugs

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    dp = models.ImageField(upload_to='profile/img', null=True)
    country = models.CharField(max_length=20, null=True)
    state = models.CharField(max_length=20, null=True)
    city = models.CharField(max_length=20, null=True)
    street_address = models.CharField(max_length=50, null=True)
    postcode = models.IntegerField(null=True)
    phone_number = models.IntegerField(null=True)
    gender = models.CharField(choices=(('Male', 'Male'), ('Female', 'Female')), max_length=10, null=True)
    wishlist_products = models.ManyToManyField(Product, blank=True, related_name='wishlist')
    cart_products = models.ManyToManyField(Product, blank=True)
    total_original = models.IntegerField(default=0)
    total_offer = models.IntegerField(default=0)
    total = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now, blank=True)
    rating = models.CharField(max_length=5, blank=True, null=True)


order_status = [(0, 'Order Placed'),
                (1, 'Order Confirmed'),
                (2, 'Packing'),
                (3, 'Shipped'),
                (4, 'Out for Delivery'),
                (5, 'Delivered'),
                (6, 'Order Cancelled'),
                (7, 'Return Request Placed'),
                (8, 'Return Request Acknowledged'),
                (9, 'Courier Service Informed'),
                (10, 'Return Product Verified'),
                (11, 'Refund Completed')
                ]


def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)


class Admin(models.Model):
    ordered_product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='admin')
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=order_status, default=0)
    order_placed_date = models.DateTimeField(default=timezone.now, blank=True, null=True)
    order_confirmed_date = models.DateTimeField(blank=True, null=True)
    packing_date = models.DateTimeField(blank=True, null=True)
    shipped_date = models.DateTimeField(blank=True, null=True)
    out_for_delivery_date = models.DateTimeField(blank=True, null=True)
    delivered_date = models.DateTimeField(default=one_week_hence, blank=True, null=True)
    order_cancelled_date = models.DateTimeField(blank=True, null=True)
    return_request_placed_date = models.DateTimeField(blank=True, null=True)
    return_request_acknowledged_date = models.DateTimeField(blank=True, null=True)
    courier_service_informed_date = models.DateTimeField(blank=True, null=True)
    return_product_verified_date = models.DateTimeField(blank=True, null=True)
    refund_completed_date = models.DateTimeField(blank=True, null=True)
    delivered = models.BooleanField(default=False)

    def __str__(self):
        return '%s ==> %s ==> %s' % (self.customer.username, self.ordered_product.title, self.get_status_display())


notification_status = [(0, 'Your Order is Placed'),
                       (1, 'Your Order is Confirmed'),
                       (2, 'Order Packed'),
                       (3, 'Your product is Shipped'),
                       (4, 'Your product is out for Delivery'),
                       (5, 'Your product is successfully Delivered'),
                       (6, 'Your order is Cancelled'),
                       (7, 'Your Return Request is Placed'),
                       (8, 'Your Return Request is Acknowledged'),
                       (9, 'Courier Service near you is Informed'),
                       (10, 'Return Product Verified'),
                       (11, 'Refund Completed')
                       ]


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Admin, on_delete=models.CASCADE)
    text = models.IntegerField(choices=notification_status, default=0)
    seen = models.BooleanField(default=False)
    close = models.BooleanField(default=False)

    def __str__(self):
        return '%s ==> %s' % (self.user.username, self.order.ordered_product.title)

products/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from .models import Profile, Comment


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'name': 'username'})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'name': 'password'})

    def clean(self, *args, **keyargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            elif not user.check_password(password):
                raise forms.ValidationError('Incorrect Password')

        return super(UserLoginForm, self).clean(*args, **keyargs)


User = get_user_model()


class UsersRegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password",
            "confirm_password",
        ]

    username = forms.CharField()
    email = forms.EmailField(label="Email")
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UsersRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            "name": "username"})
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            "name": "email"})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            "name": "password"})
        self.fields['confirm_password'].widget.attrs.update({
            'class': 'form-control',
            "name": "confirm_password"})

    def clean(self, *args, **keyargs):
        email = self.cleaned_data.get("email")
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")

        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("Email is already registered")

        username_qs = User.objects.filter(username=username)
        if username_qs.exists():
            raise forms.ValidationError("User with this username already registered")

        if len(password) < 8:
            raise forms.ValidationError("Password must have at least 8 characters")

        if password != confirm_password:
            raise forms.ValidationError("Passwords are not matching")

        return super(UsersRegisterForm, self).clean(*args, **keyargs)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'email', 'gender', 'phone_number')


class UserForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'email', 'phone_number')


class ProfilePicForm(forms.ModelForm):
    dp = forms.ImageField(widget=forms.FileInput(attrs=None))

    class Meta:
        model = Profile
        fields = ('dp',)


class AddressForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('city', 'country', 'street_address', 'postcode', 'state')


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone_number', 'city', 'country', 'street_address', 'postcode', 'state')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

products/templates/template/notification/notification.html
{% extends 'template/base.html' %}
{% load static %}
{% block content %}

<!-- ======= title ======= -->
<section class="portfolio portfolio-title">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="title-box text-center">
                    <h3 class="title-a">
                        Notifications
                    </h3>
                    <div class="line-mf"></div>
                </div>
            </div>
        </div>
    </div>
</section><!-- ======= end title ======= -->


{% if user.is_authenticated %}
{% if notification_count == 0 %}
{% include 'template/notification/notification_empty.html' %}


{% else %}
<!-- normal Notification page -->
<section class="portfolio">
    <div class="container">
        <div id="update-notification">
            {% include 'template/notification/notification_list.html' %}
        </div>
    </div>
</section>

<div id="update-notification-count" style="display: none">
    {% include 'template/notification/notification_empty.html' %}
</div>

{% endif %}


{% else %}
<!--Notification page if user is not authenticated -->
<section class="portfolio sect-pt4">
    <div class="container">
        <div class="col-md-12" data-aos="fade-up" data-aos-anchor-placement='top-bottom'>
            <div class="work-box">
                <div class="row">
                    <div class="col">
                        <h3 class="cart-empty-title">My Notifications</h3>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-4">
                        <div class="work-img cart-img">
                            <img src="/media/assets/img/cart img.png" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
                <div class="work-content">
                    <div class="row justify-content-center">
                        <div class="col-sm-8">
                            <h6 class="cart-empty-text">Login to see Notifications</h6>
                            <a class="shop-now-btn " style="margin: auto; width: 30%; color: #ffffff;"
                               href="{% url 'login' %}">Login</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}


{% endblock %}

products/templates/template/notification/notification_empty.html
<section class="portfolio">
    <div class="container">
        <div class="work-box">
            <div class="row">
                <div class="col-12">
                    <h3 class="cart-empty-title"></h3>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-5">
                    <div class="work-img cart-img">
                        <img src="/media/assets/img/cart img.png" alt="" class="img-fluid">
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-6 col-md-3">
                    <h5 class="cart-empty-text">No Notifications Yet</h5>
                    <a class="shop-now-btn" style="color: white;" href="{% url 'homepage' %}">Shop Now</a>
                </div>
            </div>
        </div>
    </div>
</section>

products/templates/template/notification/notification_info.html
{% extends 'template/base.html' %}
{% load static %}
{% block content %}


<!-- ======= title ======= -->
<section class="portfolio portfolio-title">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="title-box text-center">
                    <h3 class="title-a">
                        Notification
                    </h3>
                    <div class="line-mf"></div>
                </div>
            </div>
        </div>
    </div>
</section><!-- ======= end title ======= -->

<div class="notification">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <img src="/media/{{ notification.order.ordered_product.image_url_1 }}" alt="" class="img-fluid">
            </div>
            <div class="content col-6">
                <h3 class="indicator">{{ notification.order.ordered_product.title }}
                    {% if notification.order.status == 5 %}
                    <span class="status-indicator-green"><i class="fas fa-check-circle"></i></span>
                    {% elif notification.order.status == 6 %}
                    <span class="status-indicator-red"><i class="fas fa-check-circle"></i></span>
                    {% elif notification.order.status == 11 %}
                    <span class="status-indicator-orange"><i class="fas fa-check-circle"></i></span>
                    {% endif %}
                </h3><h6>{{ notification.get_text_display }}</h6>
                {% if notification.order.status < 5 %}
                <h6><strong>Delivery</strong> Expected by {{ notification.order.delivered_date|date:"D, j M" }}</h6>
                {% endif %}
                <div class="track-btn">
                    <a href="{% url 'track_order' order_id=notification.order.id %}" style="color: white">
                        Track Order
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

products/templates/template/notification/notification_list.html
{% for notification in notifications reversed %}
{% if notification.close == False %}
<div class="row">
    <div class="col-11 col-md-8 work-box">
        <div class="row">
            <div class="col-6 col-md-5 work-img">
                <a href="{% url 'product_detail' slug=notification.order.ordered_product.slug %}">
                    <img src="/media/{{ notification.order.ordered_product.image_url_1 }}" alt=""
                         class="img-fluid">
                </a>
            </div>
            <div class="col-6 col-md-7 cart-text">
                <h3>{{ notification.order.ordered_product.title }}
                    {% if notification.seen == False %}
                    <span class="badge badge-notification">New</span>
                    {% endif %}
                </h3>
                <a class="close-icon js-notification-close"
                   data-url="{% url 'notification_close' notification.id %}">
                    <span><i class="fas fa-times"></i></span>
                </a>
                <h6 class="indicator">{{ notification.order.get_status_display }}
                    {% if notification.order.status == 5 %}
                    <span class="status-indicator-green"><i class="fas fa-check-circle"></i></span>
                    {% elif notification.order.status == 6 %}
                    <span class="status-indicator-red"><i class="fas fa-check-circle"></i></span>
                    {% elif notification.order.status == 11 %}
                    <span class="status-indicator-orange"><i class="fas fa-check-circle"></i></span>
                    {% endif %}
                </h6>
                <div class="notification-btn">
                    <a href="{% url 'notification_info' notification_id=notification.id %}" style="color:white">More
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}